# Generated by Django 5.1.7 on 2025-06-12 22:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin_g', 'المدير العام'), ('admin', 'مدير التسجيل والحسابات'), ('dg_lessen', 'مدير الدروس'), ('admin_m', 'إدارة المقرأة'), ('teacher', 'أستاذ(ة)'), ('user', 'المراقب')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_app.branche')),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.branche')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-annee', 'numero'],
                'unique_together': {('numero', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('part_count', models.PositiveIntegerField(default=1)),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='etudiants_photos/')),
                ('payment_nature', models.CharField(choices=[('free', 'Gratuit'), ('mensuel', 'Mensuel')], default='mensuel', max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rewaya', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('tdate', models.DateField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('elmoutoune', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_desectivation', models.DateField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.CharField(choices=[('inscrit', 'Inscrit'), ('suspendu', 'Suspendu')], default='inscrit', max_length=50)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.agent')),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.branche')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.classe')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=8)),
                ('methode_paiement', models.CharField(max_length=50)),
                ('reference_transaction', models.CharField(max_length=100)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.etudiant')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.mois')),
            ],
        ),
    ]
