# Generated by Django 5.1.7 on 2025-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_etudiant_birth_date_alter_etudiant_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
