# Generated by Django 5.1.7 on 2025-08-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0002_accountcategory_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="school_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="month",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
