# Generated by Django 5.1.7 on 2025-06-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_classe_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='branche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_app.branche'),
        ),
    ]
