# Generated by Django 5.1.7 on 2025-08-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0003_transaction_account_alter_transaction_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("plus", "Plus"), ("minus", "Minus")],
                default="plus",
                max_length=20,
            ),
        ),
    ]
