# Generated by Django 5.1.7 on 2025-08-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0004_bankaccount_balance_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="school_app.account",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="school_app.employee",
            ),
        ),
    ]
