# Generated by Django 5.1.7 on 2025-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_alter_classe_branche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('session', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('completed', 'منتهية')], default='active', max_length=20)),
            ],
        ),
    ]
