# Generated by Django 5.1.7 on 2025-08-31 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0005_receipt_account_receipt_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
