# Generated by Django 5.1.7 on 2025-07-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0006_academicyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.CharField(max_length=20)),
                ("ahzab", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "memorization_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "previous_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("progress", models.CharField(blank=True, max_length=100, null=True)),
                ("absence", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "month", "year")},
            },
        ),
    ]
