# Generated by Django 5.1.7 on 2025-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0007_monthlyreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyreport",
            name="year",
            field=models.CharField(max_length=20),
        ),
    ]
