# Generated by Django 5.1.7 on 2025-09-07 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0007_alter_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="role",
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateur",
                to="school_app.job",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                choices=[
                    ("admin_g", "المدير العام"),
                    ("admin", "مدير التسجيل والحسابات"),
                    ("dg_lessen", "مدير الدروس"),
                    ("admin_m", "إدارة المقرأة"),
                    ("teacher", "أستاذ(ة)"),
                    ("user", "المراقب"),
                ],
                default="user",
                max_length=150,
                unique=True,
            ),
        ),
    ]
