# Generated by Django 5.1.7 on 2025-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0008_alter_monthlyreport_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreport",
            name="thmn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
