# Generated by Django 5.1.7 on 2025-09-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0008_remove_utilisateur_role_utilisateur_job_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utilisateur",
            old_name="job",
            new_name="role",
        ),
    ]
