# Generated by Django 5.1.7 on 2025-07-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0009_monthlyreport_thmn"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[("AM", "AM"), ("PM", "PM")], max_length=2
                    ),
                ),
                ("justified_absence", models.BooleanField(default=False)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "date", "session")},
            },
        ),
    ]
