# Generated by Django 5.1.7 on 2025-09-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0009_rename_job_utilisateur_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="branche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="school_app.branche",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="school_app.classe",
            ),
        ),
    ]
