# Generated by Django 5.1.7 on 2025-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0010_dailyabsence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyabsence",
            name="session",
            field=models.CharField(
                choices=[("صباحًا", "صباحًا"), ("مساءً", "مساءً")], max_length=6
            ),
        ),
    ]
