# Generated by Django 5.1.7 on 2025-09-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0010_employee_branche_employee_classe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="school_app.bankaccount",
            ),
            preserve_default=False,
        ),
    ]
