# Generated by Django 5.1.7 on 2025-09-20 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0011_alter_transaction_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "montant_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "date_inscription",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.activity",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "activity")},
            },
        ),
    ]
