# Generated by Django 5.1.7 on 2025-08-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0011_alter_dailyabsence_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyabsence",
            name="currentYear",
            field=models.TextField(blank=True, default="2024-2025", null=True),
        ),
    ]
