# Generated by Django 5.1.7 on 2025-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0012_inscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="is_inscrire",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
