# Generated by Django 5.1.7 on 2025-09-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0013_etudiant_is_inscrire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="branche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_app.branche",
            ),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_app.classe",
            ),
        ),
    ]
