# Generated by Django 5.1.7 on 2025-09-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0014_alter_etudiant_branche_alter_etudiant_classe"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="school_app.inscription",
            ),
        ),
    ]
