# Generated by Django 5.1.7 on 2025-10-03 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0016_garant_garantpaiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="garant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="school_app.garant",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="garant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="school_app.garant",
            ),
        ),
    ]
