# Generated by Django 5.1.7 on 2025-10-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0017_receipt_garant_transaction_garant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garant",
            name="activity",
        ),
        migrations.AddField(
            model_name="garant",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_app.account",
            ),
            preserve_default=False,
        ),
    ]
