# Generated by Django 5.1.7 on 2025-10-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0018_remove_garant_activity_garant_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garantpaiement",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="paiement",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
    ]
