# Generated by Django 5.1.7 on 2025-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0019_remove_garantpaiement_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="month",
            field=models.TextField(blank=True, null=True),
        ),
    ]
