# Generated by Django 5.1.7 on 2025-10-24 20:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0020_alter_transaction_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="date_count",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="date_inscription",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
