# Generated by Django 5.1.7 on 2025-10-31 15:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0021_etudiant_date_count_alter_etudiant_date_inscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "month",
                    models.CharField(help_text="Ex: Janvier 2025", max_length=20),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="school_app.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement de salaire",
                "verbose_name_plural": "Paiements de salaires",
                "ordering": ["-date"],
            },
        ),
    ]
