# Generated by Django 5.1.7 on 2025-10-31 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0022_salarypayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarypayment",
            name="academic_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school_app.academicyear",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salarypayment",
            name="month",
            field=models.IntegerField(),
        ),
    ]
