# Generated by Django 5.1.7 on 2025-10-31 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0023_salarypayment_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salarypayment",
            options={
                "ordering": ["-academic_year", "-month"],
                "verbose_name": "Paiement de salaire",
                "verbose_name_plural": "Paiements de salaires",
            },
        ),
        migrations.AlterField(
            model_name="salarypayment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_payments",
                to="school_app.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="salarypayment",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "01"),
                    (2, "02"),
                    (3, "03"),
                    (4, "04"),
                    (5, "05"),
                    (6, "06"),
                    (7, "07"),
                    (8, "08"),
                    (9, "09"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ],
                help_text="Mois du paiement (1-12)",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarypayment",
            constraint=models.UniqueConstraint(
                fields=("employee", "academic_year", "month"),
                name="unique_salary_per_employee_month_year",
            ),
        ),
    ]
