# Generated by Django 5.1.7 on 2025-12-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0025_permission_job_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="branche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branche",
                to="school_app.branche",
            ),
        ),
    ]
