# Generated by Django 5.1.7 on 2025-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0026_utilisateur_branche"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="branche",
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="branche",
            field=models.ManyToManyField(blank=True, to="school_app.branche"),
        ),
    ]
