# Generated by Django 5.1.7 on 2025-12-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0027_remove_utilisateur_branche_utilisateur_branche"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utilisateur",
            old_name="branche",
            new_name="branches",
        ),
    ]
