# Generated by Django 5.1.7 on 2025-12-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0028_rename_branche_utilisateur_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etudiants",
                to="school_app.classe",
            ),
        ),
    ]
