# Generated by Django 5.1.7 on 2025-12-20 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0029_alter_etudiant_classe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب التعليق")),
                ("suspend_date", models.DateField(verbose_name="تاريخ التعليق")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "total_unpaid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي المبلغ المتبقي",
                    ),
                ),
                (
                    "unpaid_months_data",
                    models.JSONField(
                        default=list, verbose_name="تفاصيل الأشهر غير المدفوعة"
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="القسط الشهري وقت التعليق",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "معلق فعلياً"),
                            ("completed", "تم إنهاء التعليق"),
                            ("cancelled", "ملغي"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="حالة التعليق",
                    ),
                ),
                (
                    "reactivation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ إعادة التنشيط"
                    ),
                ),
                (
                    "reactivation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="سبب إعادة التنشيط"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات إضافية"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التعليق بواسطة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="school_app.etudiant",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعليق طالب",
                "verbose_name_plural": "تعليقات الطلاب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="school_app__student_d0d5f2_idx",
                    ),
                    models.Index(
                        fields=["suspend_date"], name="school_app__suspend_c45b9a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="school_app__status_f0f65b_idx"
                    ),
                ],
            },
        ),
    ]
