# Generated by Django 5.1.7 on 2025-12-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0030_suspension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscription",
                to="school_app.activity",
            ),
        ),
    ]
