# Generated by Django 5.1.7 on 2025-12-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0031_alter_inscription_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seance_number",
                    models.PositiveIntegerField(
                        help_text="Numéro de la séance (1 → N)"
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="school_app.activity",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_absences",
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "ordering": ["seance_number"],
                "unique_together": {("activity", "student", "seance_number")},
            },
        ),
    ]
