# Generated by Django 5.1.7 on 2025-12-28 12:59

import django.db.models.deletion
import school_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0032_absenceactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_count", models.PositiveIntegerField(blank=True, null=True)),
                ("num_hivd", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tjwid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "moyen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "houdour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("NB", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("s1", "الفصل الأول"),
                            ("s2", "الفصل الثاني"),
                            ("s3", "الفصل الثالث"),
                            ("s4", "الفصل الرابع"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        default=school_app.models.get_default_academic_year,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ac_exams",
                        to="school_app.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
