# Generated by Django 5.1.7 on 2025-12-30 20:55

import django.db.models.deletion
import school_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0033_exam"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsElmhdara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_ab_ac", models.PositiveIntegerField(blank=True, null=True)),
                ("num_ab_no", models.PositiveIntegerField(blank=True, null=True)),
                ("NB", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "month",
                    models.CharField(
                        choices=[
                            (1, "يناير"),
                            (2, "فبراير"),
                            (3, "مارس"),
                            (4, "أبريل"),
                            (5, "مايو"),
                            (6, "يونيو"),
                            (7, "يوليو"),
                            (8, "أغسطس"),
                            (9, "سبتمبر"),
                            (10, "أكتوبر"),
                            (11, "نوفمبر"),
                            (12, "ديسمبر"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        default=school_app.models.get_default_academic_year,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ac_abs_els",
                        to="school_app.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abs_elmhdara",
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
