# Generated by Django 5.1.7 on 2025-12-31 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0034_abselmhdara"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="category",
            field=models.CharField(
                blank=True, choices=[(1, "صندوق"), (2, "بنك")], null=True
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
