# Generated by Django 5.1.7 on 2026-01-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0035_bankaccount_category_bankaccount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="etat",
            field=models.CharField(
                choices=[
                    ("inscrit", "Inscrit"),
                    ("suspendu", "Suspendu"),
                    ("en_attente", "En attente"),
                ],
                default="inscrit",
                max_length=50,
            ),
        ),
    ]
