# Generated by Django 5.1.7 on 2026-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0036_alter_etudiant_etat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="category",
            field=models.CharField(
                blank=True, choices=[(1, "صندوق"), (2, "بنك")], default=1, null=True
            ),
        ),
    ]
