# Generated by Django 5.1.7 on 2026-01-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0037_alter_bankaccount_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="name",
            field=models.CharField(default="2025", help_text="2025", max_length=9),
        ),
    ]
