# Generated by Django 5.1.7 on 2026-01-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0038_academicyear_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjustments",
                to="school_app.transaction",
            ),
        ),
    ]
