# Generated by Django 5.1.7 on 2026-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0039_transaction_related_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_adjustment",
            field=models.BooleanField(default=False),
        ),
    ]
