# Generated by Django 5.1.7 on 2026-01-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0040_transaction_is_adjustment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["-id"]},
        ),
    ]
