# Generated by Django 5.1.7 on 2026-01-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0041_alter_agent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="days",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="tdate",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
