# Generated by Django 5.1.7 on 2026-01-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0042_alter_etudiant_days_alter_etudiant_tdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="start",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
