# Generated by Django 5.1.7 on 2026-01-31 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0043_alter_etudiant_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_class",
                to="school_app.classe",
            ),
        ),
    ]
