# Generated by Django 5.1.7 on 2026-02-01 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0044_utilisateur_classe"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                choices=[
                    ("admin_g", "المدير العام"),
                    ("admin", "مدير التسجيل والحسابات"),
                    ("dg_lessen", "مدير الدروس"),
                    ("admin_m", "إدارة المقرأة"),
                    ("teacher", "أستاذ(ة)"),
                    ("user", "المراقب"),
                    ("worker", "عامل"),
                ],
                default="user",
                max_length=150,
                unique=True,
            ),
        ),
    ]
