# Generated by Django 5.1.7 on 2026-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0045_employee_user_alter_employee_number_alter_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garant",
            name="date_c",
            field=models.DateField(auto_now_add=True),
        ),
    ]
