# Generated by Django 5.1.7 on 2026-02-13 18:35

import django.db.models.deletion
import school_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0046_alter_garant_date_c"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="bankaccount",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="classe",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="etudiant",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="frais",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="garant",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="niveau",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={"ordering": ["-receipt_id"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                choices=[
                    ("admin_g", "المدير العام"),
                    ("admin", "مدير التسجيل والحسابات"),
                    ("dg_lessen", "مدير الدروس"),
                    ("admin_m", "إدارة المقرأة"),
                    ("teacher", "أستاذ(ة)"),
                    ("user", "المراقب"),
                    ("worker", "عامل"),
                    ("hakam", "حكم"),
                ],
                default="user",
                max_length=150,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        default=school_app.models.get_default_academic_year,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="school_app.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Juge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juges",
                        to="school_app.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "user")},
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "الفرع الأول"),
                            ("2", "الفرع الثاني"),
                            ("3", "الفرع الثالث"),
                            ("4", "الفرع الرابع"),
                            ("5", "الفرع الخامس"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="school_app.competition",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_participations",
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "etudiant")},
            },
        ),
        migrations.CreateModel(
            name="Tasfiya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=1)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasfiyat",
                        to="school_app.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("competition", "order")},
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personality", models.PositiveIntegerField()),
                ("voice", models.PositiveIntegerField()),
                ("performance", models.PositiveIntegerField()),
                ("memorization", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="school_app.juge",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="school_app.participant",
                    ),
                ),
                (
                    "tasfiya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="school_app.tasfiya",
                    ),
                ),
            ],
            options={
                "unique_together": {("participant", "juge", "tasfiya")},
            },
        ),
    ]
