# Generated by Django 5.1.7 on 2026-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0047_alter_account_options_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="number_of_tasfiyat",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
