# Generated by Django 5.1.7 on 2026-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0047_sabakqurra_sabakhakam_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sabakhakam",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
