# Generated by Django 5.1.7 on 2026-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0048_sabakhakam_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sabakhakam",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
