# Generated by Django 5.1.7 on 2026-02-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0049_alter_evaluation_juge"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="participant",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition_level_participations",
                to="school_app.competitionlevel",
            ),
        ),
    ]
