# Generated by Django 5.1.7 on 2026-02-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0050_competitionlevel_alter_participant_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionlevel",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition_participation",
                to="school_app.competition",
            ),
        ),
    ]
