# Generated by Django 5.1.7 on 2026-02-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0051_competitionlevel_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_paiy_month",
            field=models.BooleanField(default=False),
        ),
    ]
