# Generated by Django 5.1.7 on 2026-02-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0052_transaction_is_paiy_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="school_app.bankaccount",
            ),
        ),
    ]
