# Generated by Django 5.1.7 on 2026-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0054_alter_evaluation_memorization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="branches",
            field=models.ManyToManyField(
                blank=True, null=True, to="school_app.branche"
            ),
        ),
    ]
