# Generated by Django 5.1.7 on 2026-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0055_alter_utilisateur_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="branches",
            field=models.ManyToManyField(blank=True, to="school_app.branche"),
        ),
    ]
