# Generated by Django 5.1.7 on 2026-03-15 10:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0058_paiementtransations"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="sold_emp",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=20
            ),
        ),
    ]
