# Generated by Django 5.1.7 on 2026-03-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0059_transaction_sold_emp"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtudiantCertified",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("NNI", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("birth_date", models.DateField()),
                ("birth_city", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="etudiants/"),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "type_ijaza",
                    models.CharField(
                        choices=[("حافظ", "حافظ"), ("مجازي", "مجازي")], max_length=20
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("نافع", "نافع"), ("حفص", "حفص"), ("أخر", "أخر")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                choices=[
                    ("admin_g", "مدير عام"),
                    ("admin", "مدير التسجيل والحسابات"),
                    ("dg_lessen", "مدير الدروس"),
                    ("admin_m", "إدارة المقرأة"),
                    ("teacher", "أستاذ(ة)"),
                    ("user", "مراقب"),
                    ("worker", "عامل"),
                    ("hakam", "حكم"),
                ],
                default="user",
                max_length=150,
                unique=True,
            ),
        ),
    ]
