# Generated by Django 5.1.7 on 2026-04-04 11:12

import school_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0060_etudiantcertified_alter_job_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="etudiantcertified",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=school_app.models.upload_student_photo
            ),
        ),
    ]
