# Generated by Django 5.1.7 on 2026-04-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0061_alter_agent_options_alter_etudiantcertified_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarterlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "الفصل الأول"),
                            ("Q2", "الفصل الثاني"),
                            ("Q3", "الفصل الثالث"),
                            ("Q4", "الفصل الرابع"),
                        ],
                        max_length=2,
                    ),
                ),
                ("month_1_income", models.IntegerField(default=0)),
                ("month_1_absence", models.IntegerField(default=0)),
                ("month_2_income", models.IntegerField(default=0)),
                ("month_2_absence", models.IntegerField(default=0)),
                ("month_3_income", models.IntegerField(default=0)),
                ("month_3_absence", models.IntegerField(default=0)),
                ("total_income", models.IntegerField(default=0)),
                ("total_absence", models.IntegerField(default=0)),
                ("total_ahzab", models.IntegerField(default=0)),
                ("extra", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "quarter", "year")},
            },
        ),
    ]
