# Generated by Django 5.1.7 on 2026-04-18 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0062_quarterlyreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("certificat", "إفادة"), ("felicitation", "تهنئة")],
                        max_length=20,
                    ),
                ),
                ("date_emission", models.DateField(default=django.utils.timezone.now)),
                ("mention", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="school_app.etudiant",
                    ),
                ),
            ],
        ),
    ]
