# Generated by Django 5.1.7 on 2026-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0063_attestation"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiant",
            name="nni",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
