# Generated by Django 5.1.7 on 2026-05-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0064_etudiant_nni"),
    ]

    operations = [
        migrations.AddField(
            model_name="attestation",
            name="deceased",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attestation",
            name="elmouaza",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="attestation",
            name="etudiant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="school_app.etudiant",
            ),
        ),
        migrations.AlterField(
            model_name="attestation",
            name="type",
            field=models.CharField(
                choices=[
                    ("certificat", "إفادة"),
                    ("felicitation", "تهنئة"),
                    ("condolence", "تعزية"),
                ],
                max_length=20,
            ),
        ),
    ]
