# Generated by Django 5.1.7 on 2026-05-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0065_attestation_deceased_attestation_elmouaza_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("month", models.CharField(max_length=20)),
                ("evaluation", models.CharField(blank=True, max_length=100, null=True)),
                ("elhasila", models.CharField(blank=True, max_length=100, null=True)),
                ("progress", models.CharField(blank=True, max_length=100, null=True)),
                ("result", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "evaluation_final",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "month", "year")},
            },
        ),
    ]
