# Generated by Django 5.1.7 on 2026-05-10 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0066_evaluationresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluationresult",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
