# Generated by Django 5.1.7 on 2026-05-22 22:13

import school_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0068_evaluationperiod_evaluationresult_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="student_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=school_app.models.upload_student_photo
            ),
        ),
    ]
