# Generated by Django 5.1.7 on 2026-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0069_alter_etudiant_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiantcertified",
            name="gender",
            field=models.CharField(
                choices=[("ذكور", "ذكور"), ("إناث", "إناث")],
                default="ذكور",
                max_length=10,
            ),
        ),
    ]
