# Generated by Django 5.1.7 on 2026-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0070_etudiantcertified_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="etudiantcertified",
            name="ijazat",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
