# Generated by Django 5.1.7 on 2026-07-04 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0074_utilisateur_agent_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestation",
            name="type",
            field=models.CharField(
                choices=[
                    ("certificat", "إفادة"),
                    ("felicitation", "تهنئة"),
                    ("condolence", "تعزية"),
                    ("ethanis-students", "تهنئة طلاب"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exitcertificate",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="التاريخ"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                choices=[
                    ("admin_g", "مدير عام"),
                    ("admin", "مدير التسجيل والحسابات"),
                    ("dg_lessen", "مدير الدروس"),
                    ("admin_m", "إدارة المقرأة"),
                    ("teacher", "أستاذ(ة)"),
                    ("user", "مراقب"),
                    ("worker", "عامل"),
                    ("hakam", "حكم"),
                    ("agent", "وكيل"),
                ],
                default="user",
                max_length=150,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_id",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
