# Generated by Django 5.1.7 on 2026-07-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0075_receipt_id_custom_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20, verbose_name="الشهر")),
                (
                    "reception_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإستلام"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التسليم"
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, default="", verbose_name="النتيجة"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="الملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_receipts",
                        to="school_app.academicyear",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_receipts",
                        to="school_app.classe",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_receipts",
                        to="school_app.etudiant",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "استمارة الإستلام والتسليم",
                "ordering": ["student__student_name"],
                "unique_together": {("student", "classe", "month", "academic_year")},
            },
        ),
    ]
