# Generated by Django 5.1.7 on 2026-07-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0077_etudiant_is_residence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryreceipt",
            name="month",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="الشهر"
            ),
        ),
        migrations.CreateModel(
            name="DeliveryPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الفترة")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_periods",
                        to="school_app.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="deliveryreceipt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="deliveryreceipt",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="school_app.deliveryperiod",
                verbose_name="الفترة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryreceipt",
            unique_together={("student", "classe", "period")},
        ),
    ]
