# Generated by Django 5.1.7 on 2026-07-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0078_delivery_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etudiant",
            name="is_residence",
        ),
    ]
