# Generated by Django 5.1.7 on 2026-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0079_remove_is_residence"),
    ]

    operations = [
        migrations.AddField(
            model_name="attestation",
            name="level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="attestation",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="attestations/photos/"
            ),
        ),
        migrations.AddField(
            model_name="attestation",
            name="type_qiraa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
