# Generated by Django 5.1.7 on 2026-07-17 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0080_attestation_type_qiraa_photo_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFixedAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("الأحد", "الأحد"),
                            ("الاثنين", "الاثنين"),
                            ("الثلاثاء", "الثلاثاء"),
                            ("الأربعاء", "الأربعاء"),
                            ("الخميس", "الخميس"),
                            ("الجمعة", "الجمعة"),
                            ("السبت", "السبت"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True,
                        choices=[("صباحًا", "صباحًا"), ("مساءً", "مساءً"), ("", "الكل")],
                        default="",
                        max_length=6,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_absences",
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "day", "session")},
            },
        ),
    ]
