# Generated by Django 5.1.7 on 2026-07-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0082_push_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="TehejiReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20, verbose_name="الشهر")),
                ("year", models.CharField(max_length=10, verbose_name="العام الدراسي")),
                (
                    "louh",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="اللوح"
                    ),
                ),
                (
                    "mahfouzat",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="المحفوظات"
                    ),
                ),
                (
                    "ketaba",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="الكتابة والقراءة",
                    ),
                ),
                (
                    "taqdir",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="التقدير"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="الملاحظات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teheji_reports",
                        to="school_app.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "استمارة التهجي",
                "ordering": ["student__student_name"],
                "unique_together": {("student", "month", "year")},
            },
        ),
    ]
