# Generated by Django 5.1.7 on 2026-08-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0083_teheji_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="السنة النشطة"),
        ),
    ]
