# Generated by Django 5.1.7 on 2026-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0089_transaction_transfer_ref"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={"ordering": ["-receipt_date", "-receipt_id"]},
        ),
        migrations.AddField(
            model_name="branche",
            name="schedule_image",
            field=models.ImageField(blank=True, null=True, upload_to="schedules/"),
        ),
    ]
