# Generated by Django 5.1.7 on 2026-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0090_branche_schedule_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("pdf_file", models.FileField(upload_to="library/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
