# Generated by Django 5.1.7 on 2026-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0091_library_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarybook",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
