# Generated by Django 5.1.7 on 2026-09-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0093_library_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="notifications/"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("once", "يوم محدد"),
                            ("daily_month", "كل يوم في الشهر"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_month", models.IntegerField(blank=True, null=True)),
                ("scheduled_year", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
